apiVersion: apps/v1
kind: Deployment
metadata:
  name: gavel
spec:
  selector:
    matchLabels:
      app: gavel
  template:
    metadata:
      labels:
        app: gavel
    spec:
      containers:
      - name: gavel
        image: lexiplatform/gavel:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-configs
        - secretRef:
            name: service-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
