apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tyler-harpool/fcsf-environment.git
        revision: HEAD
        directories:
          - path: base/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "{{path.basename == 'argocd' && '0' || '1'}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/tyler-harpool/fcsf-environment.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
