apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kwasm
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
  - https://github.com/spinkube/spin-operator/releases/download/v0.4.0/spin-operator.crds.yaml
  - https://github.com/spinkube/spin-operator/releases/download/v0.1.0/spin-operator.runtime-class.yaml
  - https://github.com/spinkube/spin-operator/releases/download/v0.1.0/spin-operator.shim-executor.yaml
