apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yml: |
    entryPoints:
      metrics:
        address: ":9100"
      traefik:
        address: ":9000"
      web:
        address: ":8000"
      websecure:
        address: ":8443"
      postgres:
        address: ":5432"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-tcp
  namespace: database
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postgres
          port: 5432
