apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-tcp
  namespace: database
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`postgres.rancher.localhost`)
      services:
        - name: postgres
          namespace: database
          port: 5432
