apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
stringData:
  admin.password: $2y$10$5SpudhFIcqwrGKzG79AHCev03tbhCbXOebC9ws1K6i8RUmJiUPG0a
  admin.passwordMtime: "2022-01-01T00:00:00Z"
