apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../base
  - traefik.yaml
  - configmap.yaml
patches:
  - path: argocd-cmd-params-cm.yaml
  - target:
      group: ""
      version: v1
      kind: Secret
      name: argocd-secret
    path: argocd-secret.yaml
