apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argooperatorrolebinding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argooperator
  namespace: argo
roleRef:
  kind: Role
  name: argooperatorrole
  apiGroup: rbac.authorization.k8s.io
