    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: argocd-traefik-binding
    subjects:
      - kind: ServiceAccount
        name: argocd-application-controller
        namespace: argocd
    roleRef:
      kind: ClusterRole
      name: argocd-traefik-role
      apiGroup: rbac.authorization.k8s.io
