apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - deployment.yaml
  - appsets/
  # - argocd-traefik-clusterrolebinding.yaml


images:
- name: quay.io/argoproj/argocd
  newTag: v2.11.3
