# base/oauth/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secrets
    template:
      engineVersion: v2
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
  - secretKey: client_id
    remoteRef:
      key: kv/data/oauth2-proxy
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: kv/data/oauth2-proxy
      property: client_secret
  - secretKey: cookie_secret
    remoteRef:
      key: kv/data/oauth2-proxy
      property: cookie_secret
