apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
- ingress.yaml
- namespace.yaml
helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.25.0
  releaseName: vault
  namespace: vault
  includeCRDs: true
  valuesInline:
    injector:
      enabled: false
    server:
      ha:
        enabled: true
        replicas: 1
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
