apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
- ../../base
- ingress.yaml
patches:
- target:
    kind: ConfigMap
    name: vault-config
  patch: |
    - op: replace
      path: /data/extraconfig-from-values.hcl
      value: |
        ui = true
        disable_mlock = true
        storage "raft" {
          path = "/vault/data"
          node_id = "node1"
        }
        listener "tcp" {
          tls_disable = "true"
          address = "0.0.0.0:8200"
        }
        api_addr = "http://0.0.0.0:8200"
        cluster_addr = "https://0.0.0.0:8201"
        service_registration "kubernetes" {}
