apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
- ../../base

patches:
- target:
    kind: Ingress
    name: vault-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: vault.rancher.localhost
