apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: vault.rancher.localhost
  target:
    kind: Ingress
    name: vault-ingress
