apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: eso-secret-store
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
