
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "2"
  name: external-secrets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd


spec:
  # The project the application belongs to.
  project: infrastructure

  # Source of the application manifests
  source:
    repoURL: https://charts.external-secrets.io/ # Can point to either a Helm chart repo or a git repo.
    targetRevision: 0.7.2   # For Helm, this refers to the chart version.

    # helm specific config
    chart: external-secrets   # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      # Release name override (defaults to application name)
      releaseName: external-secrets
      # Optional Helm version to template with. If omitted it will fall back to look at the 'apiVersion' in Chart.yaml
      # and decide which Helm binary to use automatically. This field can be either 'v2' or 'v3'.
      version: v3

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
