apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
- namespace.yaml

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.10.5
  releaseName: external-secrets
  namespace: external-secrets
  includeCRDs: true
  valuesInline:
    webhook:
      create: true
    certController:
      create: false
    crd:
      conversion:
        enabled: false
