# First, ensure the vault namespace exists
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
# The ArgoCD Application configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd        # Application must be in argocd namespace
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.18.1
    chart: vault           # Specifies this is a Helm chart
    helm:
      values: |-
        injector:
          enabled: false
        server:
          affinity: ""
          ha:
            enabled: true
            replicas: 1
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true
                disable_mlock = true
                storage "raft" {
                  path = "/vault/data"
                  node_id = "node1"
                }
                listener "tcp" {
                  tls_disable = 1
                  address = "0.0.0.0:8200"
                }
                api_addr = "http://0.0.0.0:8200"
                cluster_addr = "https://0.0.0.0:8201"
                service_registration "kubernetes" {}
  destination:
    server: https://kubernetes.default.svc
    namespace: vault       # Deploy Vault to the vault namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
# Add an ingress for the Vault UI
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: vault.rancher.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
