apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-config
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-config
  template:
    metadata:
      labels:
        app: vault-config
    spec:
      serviceAccountName: vault-auth
      initContainers:
      - name: wait-for-vault-init
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          until kubectl get secret vault-token -n vault --no-headers && \
                kubectl get secret vault-unseal-keys -n vault --no-headers; do
            echo "Waiting for vault secrets..."
            sleep 5
          done
          echo "Vault secrets found!"
      containers:
      - name: vault-config
        image: hashicorp/vault:1.13.3
        command: ["/bin/sh"]
        args: ["/scripts/configure.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        volumeMounts:
        - name: config-script
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: config-script
        configMap:
          name: vault-config-script
          defaultMode: 0755
