apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init-script
  namespace: vault
data:
  init.sh: |
    #!/bin/sh
    set -e

    echo "Checking Vault status..."

    # Check if Vault is already initialized
    if vault status | grep -q 'Initialized.*true'; then
      echo "Vault is already initialized. Checking for existing keys..."

      # Check if secrets already exist
      if ! kubectl get secret vault-token -n $KUBERNETES_NAMESPACE >/dev/null 2>&1; then
        echo "Error: Vault is initialized but secrets are missing. Manual intervention required."
        exit 1
      else
        echo "Existing secrets found. Nothing to do."
        # Keep container running for debugging
        tail -f /dev/null
      fi
    else
      echo "Initializing Vault..."
      INIT_OUTPUT=$(vault operator init)
      echo "$INIT_OUTPUT" > /vault/keys/init-output.json

      # Extract and store root token
      ROOT_TOKEN=$(echo "$INIT_OUTPUT" | grep 'Initial Root Token:' | awk '{print $NF}')
      kubectl -n $KUBERNETES_NAMESPACE create secret generic vault-token \
        --from-literal=token=$ROOT_TOKEN \
        --dry-run=client -o yaml | kubectl apply -f -

      # Extract and store unseal keys
      UNSEAL_KEYS=$(echo "$INIT_OUTPUT" | grep 'Unseal Key' | awk '{print $NF}' | tr '\n' ' ')
      kubectl -n $KUBERNETES_NAMESPACE create secret generic vault-unseal-keys \
        --from-literal=keys="$UNSEAL_KEYS" \
        --dry-run=client -o yaml | kubectl apply -f -
    fi

    # Keep the pod running for debugging
    tail -f /dev/null
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config-script
  namespace: vault
data:
  configure.sh: |
    #!/bin/sh
    set -e

    vault auth enable kubernetes || true

    vault write auth/kubernetes/config \
      kubernetes_host="https://kubernetes.default.svc" \
      token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
      kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      issuer="https://kubernetes.default.svc.cluster.local"

    vault policy write oauth-policy - <<EOF
    path "kv/data/oauth2-proxy/*" {
      capabilities = ["read", "list"]
    }
    path "kv/metadata/oauth2-proxy/*" {
      capabilities = ["list"]
    }
    EOF

    vault write auth/kubernetes/role/oauth2-proxy \
      bound_service_account_names=oauth2-proxy \
      bound_service_account_namespaces=oauth \
      policies=oauth-policy \
      ttl=1h

    vault secrets enable -path=kv -version=2 kv || true

    # Keep container running
    tail -f /dev/null
