apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-init
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-init
  template:
    metadata:
      labels:
        app: vault-init
    spec:
      serviceAccountName: vault-auth
      initContainers:
      - name: wait-for-vault
        image: busybox
        command: ['sh', '-c', 'cp /bin/vault /vault-binary/vault && chmod +x /vault-binary/vault']
      - name: copy-vault-binary  # Add init container to copy vault binary
        image: hashicorp/vault:1.13.3
        command: ['sh', '-c', 'cp /bin/vault /vault-binary/vault']
        volumeMounts:
        - name: vault-binary
          mountPath: /vault-binary
      containers:
      - name: vault-init
        image: bitnami/kubectl:latest # Changed the image to include kubectl
        command: ["/bin/sh"]
        args: ["/scripts/init.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc:8200"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VAULT_BIN  # Add path to vault binary
          value: "/usr/local/bin/vault"
        volumeMounts:
        - name: init-script
          mountPath: /scripts
          readOnly: true
        - name: vault-keys
          mountPath: /vault/keys
        - name: vault-binary  # Add volume mount for vault binary
          mountPath: /usr/local/bin/vault
      volumes:
      - name: init-script
        configMap:
          name: vault-init-script
          defaultMode: 0755
      - name: vault-keys
        emptyDir: {}
      - name: vault-binary  # Add volume for vault binary
        emptyDir: {}
