apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-init
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-init
  template:
    metadata:
      labels:
        app: vault-init
    spec:
      serviceAccountName: vault-auth
      initContainers:
      - name: wait-for-vault
        image: busybox
        command: ['sh', '-c', '
          until nc -z vault-0.vault-internal 8200 || nc -z vault.vault.svc 8200;
          do echo "waiting for vault to listen on port 8200"; sleep 2; done']
      containers:
      - name: vault-init
        image: hashicorp/vault:1.13.3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command: ["/bin/sh"]
        args: ["/scripts/init.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc:8200"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATH
          value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/kubectl"
        volumeMounts:
        - name: init-script
          mountPath: /scripts
          readOnly: true
        - name: vault-keys
          mountPath: /vault/keys
        - name: kubectl-binary
          mountPath: /kubectl
      - name: kubectl-sidecar
        image: bitnami/kubectl:latest
        command: ['cp', '/opt/bitnami/kubectl/bin/kubectl', '/kubectl/kubectl']
        volumeMounts:
        - name: kubectl-binary
          mountPath: /kubectl
      volumes:
      - name: init-script
        configMap:
          name: vault-init-script
          defaultMode: 0755
      - name: vault-keys
        emptyDir: {}
      - name: kubectl-binary
        emptyDir:
          medium: Memory
