apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-init
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-init
  template:
    metadata:
      labels:
        app: vault-init
    spec:
      serviceAccountName: vault-auth
      initContainers:
        - name: wait-for-vault
          image: busybox
          command: ['sh', '-c', '
            until nc -z vault-0.vault-internal 8200 || nc -z vault.vault.svc 8200;
            do echo "waiting for vault to listen on port 8200"; sleep 2; done']
      containers:
      - name: vault-init
        image: hashicorp/vault:1.13.3
        command: ["/bin/sh"]
        args: ["/scripts/init.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc:8200"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: init-script
          mountPath: /scripts
          readOnly: true
        - name: vault-keys
          mountPath: /vault/keys
      volumes:
      - name: init-script
        configMap:
          name: vault-init-script
          defaultMode: 0755
      - name: vault-keys
        emptyDir: {}
