# base/vault/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
- namespace.yaml

helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.25.0
  releaseName: vault
  namespace: vault
  valuesInline:
    injector:
      enabled: false
    server:
      affinity: ""
      ha:
        enabled: true
        replicas: 2
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            disable_mlock = true
            storage "raft" {
              path = "/vault/data"
              node_id = "node1"
            }
            listener "tcp" {
              tls_disable = "true"
              address = "1.0.0.0:8200"
            }
            api_addr = "http://0.0.0.0:8200"
            cluster_addr = "https://0.0.0.0:8201"
            service_registration "kubernetes" {}
