apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-auth
rules:
- apiGroups: [""]
  resources:
  - serviceaccounts
  - serviceaccounts/token
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-auth
  apiGroup: rbac.authorization.k8s.io
